// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD49_PPW84RnRkWpgA6T6zsEwC7t6wmt-w',
    appId: '1:851197053748:web:7070a3c7c4c42fe26e3361',
    messagingSenderId: '851197053748',
    projectId: 'shaurya-pay',
    authDomain: 'shaurya-pay.firebaseapp.com',
    storageBucket: 'shaurya-pay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3j8NYdrvHJnZC8Z5t7eq0vcctJuLdbYA',
    appId: '1:851197053748:android:353c6db18c2387e76e3361',
    messagingSenderId: '851197053748',
    projectId: 'shaurya-pay',
    storageBucket: 'shaurya-pay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvV-MJqMcUikm1iTTMDeq170YKeqcK3k',
    appId: '1:851197053748:ios:54ce2308e7084cce6e3361',
    messagingSenderId: '851197053748',
    projectId: 'shaurya-pay',
    storageBucket: 'shaurya-pay.appspot.com',
    iosBundleId: 'com.example.fastTag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQvV-MJqMcUikm1iTTMDeq170YKeqcK3k',
    appId: '1:851197053748:ios:54ce2308e7084cce6e3361',
    messagingSenderId: '851197053748',
    projectId: 'shaurya-pay',
    storageBucket: 'shaurya-pay.appspot.com',
    iosBundleId: 'com.example.fastTag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD49_PPW84RnRkWpgA6T6zsEwC7t6wmt-w',
    appId: '1:851197053748:web:64f67f9be19c28566e3361',
    messagingSenderId: '851197053748',
    projectId: 'shaurya-pay',
    authDomain: 'shaurya-pay.firebaseapp.com',
    storageBucket: 'shaurya-pay.appspot.com',
  );
}
