// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxkdQCFYV2jHShuQ9C8bpzB8_3aUAKgWA',
    appId: '1:315964127831:web:b85c0615d5e39f19cf8112',
    messagingSenderId: '315964127831',
    projectId: 'shaurya-pay-88647',
    authDomain: 'shaurya-pay-88647.firebaseapp.com',
    storageBucket: 'shaurya-pay-88647.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwjURZv7E8dxYkNJTt_hhQhyGuoTyrSEw',
    appId: '1:315964127831:android:3ada144364428f38cf8112',
    messagingSenderId: '315964127831',
    projectId: 'shaurya-pay-88647',
    storageBucket: 'shaurya-pay-88647.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPCS3egl6k4h3zgnTZDbbTjiSZ1GzXin8',
    appId: '1:315964127831:ios:975533e6302209bfcf8112',
    messagingSenderId: '315964127831',
    projectId: 'shaurya-pay-88647',
    storageBucket: 'shaurya-pay-88647.appspot.com',
    iosBundleId: 'com.example.fastTag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPCS3egl6k4h3zgnTZDbbTjiSZ1GzXin8',
    appId: '1:315964127831:ios:975533e6302209bfcf8112',
    messagingSenderId: '315964127831',
    projectId: 'shaurya-pay-88647',
    storageBucket: 'shaurya-pay-88647.appspot.com',
    iosBundleId: 'com.example.fastTag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxkdQCFYV2jHShuQ9C8bpzB8_3aUAKgWA',
    appId: '1:315964127831:web:a488dff6260576edcf8112',
    messagingSenderId: '315964127831',
    projectId: 'shaurya-pay-88647',
    authDomain: 'shaurya-pay-88647.firebaseapp.com',
    storageBucket: 'shaurya-pay-88647.appspot.com',
  );

}